version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.0

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: 083849978945.dkr.ecr.us-east-1.amazonaws.com
          aws-access-key-id: AKIARHBOZERA4PUMEFEA
          aws-secret-access-key: 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
          create-repo: true
          dockerfile: Dockerfile
          path: .
          region: us-east-1
          repo: circleci-ecr
          tag: "$CIRCLE_SHA1"
